### ISSUE TITLE
Consider Kubernetes Auto-Detection

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-docker#115]
When a container detects it's running inside k8s cluster it should try to use the k8s discovery strategy by default. 

Reasoning: Currently the container always defaults to multicast. This creates hard-to-reason about issues when running on k8s. 

Example:
I'm having 2 k8s nodes running 3 Hazelcast pods. Only 2 pods found each other and 1 was isolated. It took me quite some time to figure out it was caused by the multicast discovery strategy. 

The [readme.md](https://github.com/hazelcast/hazelcast-docker/blob/e4e407d544eb361be32b63735fdc681d8fb35d90/README.md#hazelcast-kubernetes) even says: "Hazelcast is prepared to work in the Kubernetes environment. " So I thought it would work out of the box, but that's not the case.

I think the default config could try to enable the k8s discovery based on some env. properties. 

Possible issue:  k8s API requires RBAC configuration and it will fail when it does not have sufficient permission. However it's still better than half-working default. It would give you a quick feedback and a sensible error message with a hint how to fix it.

**Comment by leszko** [comment]
It's a very good idea Jaromir! I think we can solve it at two levels:

1. Docker image could have a script to modify on-the-fly which `hazelcast.xml` is used and if it detects it's run in k8, it applies Kubernetes Discovery Strategy with the default parameters (we don't touch any core code, it's just in the Docker image).

2. Implement the `<auto-discovery>` parameter in the core configuration. Then, extend the SPI to have a check if it's run in this particular environment. Then, if a user defines `<auto-discovery enabled="true"/>`, then Hazelcast walks through all available discovery plugins and checks which one is the right one.

Both solutions will work, however I somehow favor the second one, because it's super convenient for the user. Like Spring Boot, no configuration and it just works on every environment: AWS, Kubernetes, or any other we'll put later into hazelcast-all.

@jerrinot , Wdyt?

**Comment by jerrinot** [comment]
@leszko so what strategies you can auto-enable? k8s - by checking a presence of env. variable. what else?

**Comment by leszko** [comment]
hazelcast-kubernetes: Yes (by checking the files that are automatically put into the container)
hazelcast-aws: Yes (by checking the Metadata endpoint: http://169.254.169.254/latest/meta-data/)
hazelcast-gcp: Yes (by checking the instance metadata endpoint)

hazelcast-azure: ? (probably yes, but the Azure plugin requires re-writing anyway)

hazelcast-eureka: No (because Eureka server can be anywhere)

**Comment by jerrinot** [comment]
so what if you are running our Docker image in Google g8s? 
I assume the `http://169.254.169.254/latest/meta-data` endpoint is still available from pods?

**Comment by leszko** [comment]
Yeah, you're probably right that there can be more than one matching strategy. But it should be always possible to give some priorities. Like `hazelcast-kubernetes` should be always checked before `hazelcast-gcp`. 
Concerning the default values, I would treat it something like Spring Boot, meaning that it should just work, but on the production you definitely need to do some configuration. I guess it's possible to do for each strategy.

**Comment by jerrinot** [comment]
ok. so I see 2 possible implementations:
1. something tailored to a few specific strategies. when you enable it then it has a list of hard-coded things to try: 1st try k8s. then azure, then foo and as a last resort: multicast. pros: simple to implement, no changes in the Discovery SPI needed.
2. have something more general. extend the Discovery SPI so each strategy can tell to Core whether it's usable in a given environment. but then you have to deal with conflicts, maybe introduce priorities, etc..
pros: custom strategies can participate. cons: quite a bit of work, harder to reason about(?)

**Comment by leszko** [comment]
I'd go for the first solution and include at least the plugins we have in `hazelcast-all`. That would mean that all other plugins and the community plugins are not included in the auto-discovery, but I think it's alright.

Saying that, I think the implementation needs to be done in the Core (not necessarily by the Core team, I can implement it, it should be quick). I'd add a new configuration parameter, like I mentioned before `<auto-discovery enabled="true"/>`. Otherwise, it could get confusing to users. Or do you think we should just make it automatic in 4.0 without adding any flags? Wdyt?

**Comment by jerrinot** [comment]
I think it should be explicitly enabled. and then we can enable it by default in our Docker config.

**Comment by leszko** [comment]
Sounds like a plan! 👍

**Comment by mesutcelik** [comment]
Do we have a sensible defaults in all discovery plugins? I know that for instance azure needs some keys to be defined. We need to first check plugins if they are ready for zero config usage then `<auto-discovery enabled="true"/>` seems logical

**Comment by mesutcelik** [comment]
I also feel like ECS (EC2 or Fargate mode) deserves the autodetection.

**Comment by leszko** [comment]
The autodiscovery will work fine for sure for: `hazelcast-kubernetes`, `hazelcast-aws`, and `hazelcast-gcp`. Obviously, you'll still have some requirements for the envioronments (kubernetes: RBAC must be configured, AWS: IAM Role which allows API queries must be assigned, GCP: Service Account with read access to GCP API must be assigned).

Concerning ECS, I think while the implementation on ECS, we should make the default parameters just work. @googlielmo .

**Comment by leszko** [comment]
Related PRD: https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1720386612/Discovery+Strategy+Auto+Detection

**Comment by jerrinot** [comment]
superseded by https://github.com/hazelcast/hazelcast/pull/17112
