### ISSUE TITLE
Enable changing logging level as non-root user

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-docker#128]
Currently, you can change LOGGING_LEVEL only as the root user.

**Comment by leszko** [comment]
Related to #129 . Maybe if we include some other logging library, then it won't be an issue anymore.

**Comment by enozcan** [comment]
With daf0aa2, the logging level is now set by env:
https://github.com/hazelcast/hazelcast-docker/blob/c99c4dd57f0d3a31926d9173ffa86565f0206649/hazelcast-oss/start-hazelcast.sh#L25

rather than editing JUL properties file as it was before:

https://github.com/hazelcast/hazelcast-docker/blob/78caac8072dd5ce678003d9aa2e886a53e658183/hazelcast-oss/start-hazelcast.sh#L25

Thus non-root users also should be able to change the level now.


The charts [doc](https://github.com/hazelcast/charts/tree/master/stable/hazelcast#configuration) might need to be updated accordingly (cc @hasancelik @leszko):

> note that changing this value requires setting securityContext.runAsUser to 0 and securityContext.readOnlyRootFilesystem to false

**Comment by hasancelik** [comment]
@enozcan you are right, could you create PR for hazelcast and hazelcast-enterprise chart?

**Comment by enozcan** [comment]
Sure, I will take care of the charts changes. Closing this as it's not the case anymore.
