### ISSUE TITLE
CVE security vulnerabilities for 4.1.1

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-docker#229]
`hazelcast` and `hazelcast-enterprise` list today as exposed to 1 security vulnerability :    ALPINE-CVE-2020-1971   

which will be due to `FROM alpine:3.13.0`

See also, https://github.com/hazelcast/hazelcast-docker/issues/166 .. these issues are not listed so perhaps fixed

**Comment by leszko** [comment]
@enozcan could you check if it's detected by our GH Action?

**Comment by enozcan** [comment]
@leszko I don't see CVE-2020-1971 among the reported ones last night: https://github.com/hazelcast/hazelcast-docker/runs/1759358547?check_suite_focus=true

**Comment by hasancelik** [comment]
@leszko @enozcan `ALPINE-CVE-2020-1971` is already fixed with `alpine-3.12.3`:
https://github.com/docker-library/official-images/pull/9295
We have released 4.1.1 OS and EE images with `alpine-3.12.2`:
https://github.com/hazelcast/hazelcast-docker/commit/8e531f5a8a87c268d95dd3cad9abf6693d70c9e8#diff-fcaf45f62a2fdc483b0edd5506e0bb6a7fbd11bba72dedcef1ab36117aecda20L1
Current OS master is based on `alpine-3.13.0` and EE master is based on `registry.access.redhat.com/ubi8/ubi-minimal:8.3` so we do not need to worry about `ALPINE-CVE-2020-1971`.

BTW, our scan actions did not detect this CVE for `4.1.1`: 
https://github.com/hazelcast/hazelcast-docker/runs/1594474636

**Comment by neilstevenson** [comment]
Could it be a false detection ?
