### ISSUE TITLE
Remove printing the Hazelcast license key while starting Hazelcast

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-docker#248]
Currently, we print `JAVA_OPTS` while starting Hazelcast. And Hazelcast License key is printed as well. Since it's sensitive information, we should not print it.

**Comment by hasancelik** [comment]
With https://github.com/hazelcast/hazelcast-docker/pull/213 PR, we will start to use [Overriding Configuration](https://docs.hazelcast.com/imdg/latest/configuration/overriding-configuration-settings.html) feature for license key. But still the issue will be valid because [ExternalConfigurationOverride](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/config/override/ExternalConfigurationOverride.java#L84) log all external config entries:
```
$ docker run -e HZ_LICENSEKEY="ENT...." hazelcast/hazelcast-enterprise
...
2021-03-16 08:09:41,014 [ INFO] [main] [c.h.i.c.o.ExternalConfigurationOverride]: Detected external configuration entries in environment variables: [hazelcast.licensekey=ENT....]
...
```
We can exclude license key from logs via small change at Hazelcast core side:
```
                LOGGER.info(format("Detected external configuration entries in %s: [%s]",
                  configProvider.name(),
                  properties.entrySet().stream()
                          .filter(e -> !unprocessed.containsKey(e.getKey()) && !e.getKey().equals("hazelcast.licensekey"))
                          .map(e -> e.getKey() + "=" + e.getValue())
                          .collect(joining(","))));
```

**Comment by leszko** [comment]
I think we should exclude it in Core. Wdyt? @pivovarit @vbekiaris @mmedenjak

**Comment by pivovarit** [comment]
Agreed

**Comment by mmedenjak** [comment]
😬 yes, please :)

**Comment by mmedenjak** [comment]
Can you open up an issue about it, or better yet send the PR if you're up for it?

**Comment by leszko** [comment]
@hasancelik if you already have the code, could you send a PR to the core repo? Or if you don't have time, then just open a GH Issue.
