### ISSUE TITLE
Hazelcast Client on Host fails to work with Hazelcast Cluster in Docker

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast-docker#56]
I have a simple use case where I want to spin up a Hazelcast Cluster in Docker on my laptop but I want to connect to that cluster with a Hazelcast Client I am coding on my local IDE on my host O/S.

Simple enough to reproduce, start 2 Hazelcast Docker cluster instances...

```
docker run -it -p 5701:5701 hazelcast/hazelcast
docker run -it -p 5702:5702 hazelcast/hazelcast
```

Start a client on the host O/S and connect on 127.0.0.1:5701 and reports back…

```
Members [2] {
	Member [172.17.0.2]:5701 - a126f9e6-16fe-443a-b9a0-ee5fe04949b3
	Member [172.17.0.3]:5702 - 353a41ef-6bc0-489a-8944-0e1de7c39f34
}
```

Any other operations afterwards just timeouts eventually reporting....

```
Caused by: java.io.IOException: No available connection to address [172.17.0.3]:5702
```

**Comment by dbrimley** [comment]
It seems like the smart client on the Host O/S is trying to connect to the private docker IP addresses?

**Comment by dbrimley** [comment]
Using public addresses and net doesn't even form a cluster...

docker run -it -d -p 5701:5701 -e JAVA_OPTS="-Dhazelcast.local.publicAddress=192.168.0.6:5701" --net hazelcast-network hazelcast/hazelcast:3.9.3
docker run -it -d -p 5702:5702 -e JAVA_OPTS="-Dhazelcast.local.publicAddress=192.168.0.6:5702" --net hazelcast-network hazelcast/hazelcast:3.9.3

**Comment by leszko** [comment]
I think you're publishing the wrong port in your second "docker run" command. The port inside the container is always: "5701". Could you try the following?

```
docker run -it -p 5701:5701 hazelcast/hazelcast
docker run -it -p 5702:5701 hazelcast/hazelcast 
```

Then your hazelcast instances will be published as: "localhost:5701" and "localhost:5702" (instead of "localhost" you can use any of your network interfaces, since "-p" publishes to all your host network interfaces).

**Comment by leszko** [comment]
Ok, I've checked and you're right: changing the ports that are published is not enough (but still you should use: "-p 5702:5701", not "-p 5702:5702"). The second issue is that hazelcast instances use the internal container IP address instead of the host IP address. It's something Mesut mentioned. So you need to use the following commands:

```
docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<host_interface_ip>:5701" -it -p 5701:5701 hazelcast/hazelcast
docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<host_interface_ip>:5702" -it -p 5702:5701 hazelcast/hazelcast 
```
where `<host_interface_ip>` is the IP of the host machine. Actually any interface should do (because you publish ports to all interfaces), just don't use `localhost` or `127.0.0.1` (because container will address their own localhosts). E.g. use the address you'll find with `ifconfig/ipconfig` that starts from "192.168.0.*". I tried and this works. No need to change anything in the Client.

**Comment by dbrimley** [comment]
A cluster doesn't form when I try this...

`docker run -it -d -p 5701:5701 -e JAVA_OPTS="-Dhazelcast.local.publicAddress=192.168.1.2:5701" hazelcast/hazelcast:3.9.3`
`docker run -it -d -p 5702:5701 -e JAVA_OPTS="-Dhazelcast.local.publicAddress=192.168.1.2:5702" hazelcast/hazelcast:3.9.3`

**Comment by leszko** [comment]
Discussed Offline. 

I'll add a doc to the README in hazelcast-docker and then close this issue.

**Comment by leszko** [comment]
https://github.com/hazelcast/hazelcast-docker/pull/57

**Comment by garyrg9** [comment]
Thanks so much for this thread. I got my console app working...now the sky is the limit!

**Comment by sach429** [comment]
> Ok, I've checked and you're right: changing the ports that are published is not enough (but still you should use: "-p 5702:5701", not "-p 5702:5702"). The second issue is that hazelcast instances use the internal container IP address instead of the host IP address. It's something Mesut mentioned. So you need to use the following commands:
> 
> ```
> docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<host_interface_ip>:5701" -it -p 5701:5701 hazelcast/hazelcast
> docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<host_interface_ip>:5702" -it -p 5702:5701 hazelcast/hazelcast 
> ```
> 
> where `<host_interface_ip>` is the IP of the host machine. Actually any interface should do (because you publish ports to all interfaces), just don't use `localhost` or `127.0.0.1` (because container will address their own localhosts). E.g. use the address you'll find with `ifconfig/ipconfig` that starts from "192.168.0.*". I tried and this works. No need to change anything in the Client.

Is it necessary for the two docker instances to run in the same docker network? For eg. if I do the following:
`
docker network create network-1
docker network create network-2
`

followed by a slight modification to the mentioned commands
`
docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<host_interface_ip>:5701" -it --net network-1 -p 5701:5701 hazelcast/hazelcast
docker run -e JAVA_OPTS="-Dhazelcast.local.publicAddress=<host_interface_ip>:5702" -it --net network-2 -p 5702:5701 hazelcast/hazelcast 
`
the cluster isn't formed
