### ISSUE TITLE
Upgrading running Kubernetes cluster with no downtime

### ISSUE THREAD

**Issue by jmif** [hazelcast/hazelcast-docker#59]
Hi there,

Is it possible to upgrade a running non enterprise Kubernetes based Hazelcast cluster with no downtime?  We're aware of the Rolling Member Upgrades feature released in 3.8 however this seems to be an enterprise feature.  Is there any similar feature and / or recommended procedure for non enterprise users?

Thanks!

**Comment by mesutcelik** [comment]
Hi @jmif ,
You can always implement patch level upgrades in OSS hazelcast cluster. Member running in different patch levels is fine. 
If your aim is zero downtime then I have unfortunately no recommended solution for you. 
However, you can follow something like the following if you consider a calculated downtime based on your architecture

1. create a new cluster with a latest version of hazelcast
2. create an application moving all data from source to cluster
3. switch source cluster to PASSIVE so that writes are not allowed but reads
4. start running data transfer application.
5. redirect your applications to new cluster
6. decommision the source cluster.

That can only be used in client/server topology and downtime can be calculated based on how fast you can move data around....

I am closing this issue but you can always ask questions to [Hazelcast Google Group](https://groups.google.com/forum/#!forum/hazelcast).
