### ISSUE TITLE
Print a warning when British spelling of "License" is used 

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-docker#68]
I was banging my head against a keyboard because my Hazelcast docker image refused to start. 
It took me to a while to realize I set the `HZ_LICENCE_KEY` env. property instead of `HZ_LICENSE_KEY`. 

In the UK "license" is used as a verb while a noun is spelled as "licence". 
I think a warning here would be nice. 

Right now a misspelled key is silently ignored.

**Comment by leszko** [comment]
@jerrinot , 

1. Do we have a warning in hazelcast root if you misspell it: `-Dhazelcast.enterprise.licence.key` instead of `-Dhazelcast.enterprise.license.key`? That could also be helpful.

2. Warning would be nice but I would not really limit to the misspelling, but in general validate that `HZ_LICENSE_KEY` is specified. Wdyt?

**Comment by jerrinot** [comment]
@leszko:
#1: good idea. can you please create an issue in the core project?
#2: yes. also a good idea. I would still vote to print an explicit warning when you detect there is no `HZ_LICENSE_KEY`, but there is `HZ_LICENCE_KEY`

**Comment by leszko** [comment]
1. Created: https://github.com/hazelcast/hazelcast/issues/13161
2. Ok :)

**Comment by ahmetmircik** [comment]
encountered same issue, a warning would be helpful.
