### ISSUE TITLE
Consider convenience for debugging

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-docker#69]
It would be nice to add some convenience for easy debugging. 

My idea is to pass a parameter to the image to start JVM with JPDA port open + also expose this port somehow. 

Then it would be easy to run the image locally and attach a debugger running on my host machine.

**Comment by leszko** [comment]
@jerrinot , do you have any particular use case in mind? I think that everything you mentioned is possible to do with the current Docker image:
- You can pass any Java options you like to Hazelcast with the JAVA_OPTS variable
- You can publish any port you like outside container

What else do you need for debugging?

**Comment by leszko** [comment]
I see. Yeah, then you could run it again with the remote debug session from IntelliJ and check. I actually never debugged this way, since Dockerfile usually contains almost zero business logic, so it's simpler just to run the application directly from IntelliJ than run Docker container and configure remote debug.

Saying that, we can leave this issue open and document it, since it can be helpful.

**Comment by ps-jay** [comment]
I guess if we're turning this into a documentation issue, it would also be good to document how to open JMX & the JMX ports.
